// <auto-generated />
using System;
using InfrastructureLayer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfrastructureLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250522132119_RemovedOldAccountInfoModel")]
    partial class RemovedOldAccountInfoModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainLayer.Models.Admin.AdminModel", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AdminId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("DomainLayer.Models.Contractor.ContractorModel", b =>
                {
                    b.Property<Guid>("ContractorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasicHourlyRate")
                        .HasColumnType("money");

                    b.Property<decimal>("MaximumWeeklyHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContractorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("DomainLayer.Models.ContractorAttendanceLog.ContractorAttendanceLogModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("TimeIn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId");

                    b.ToTable("ContractorAttendanceLogModel");
                });

            modelBuilder.Entity("DomainLayer.Models.ContractorPayslip.ContractorPayslipModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AppliedHourlyRate")
                        .HasColumnType("money");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("money");

                    b.Property<DateOnly>("PayDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalHoursRendered")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId");

                    b.ToTable("ContractorPayslipModel");
                });

            modelBuilder.Entity("DomainLayer.Models.Department.DepartmentModel", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("DomainLayer.Models.Employee.EmployeeModel", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Absences")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("BasicDailyRate")
                        .HasColumnType("money");

                    b.Property<decimal>("BasicMonthlyRate")
                        .HasColumnType("money");

                    b.Property<TimeOnly>("DefaultBreakTimeEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("DefaultBreakTimeStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("DefaultWorkShiftEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("DefaultWorkShiftStart")
                        .HasColumnType("time");

                    b.Property<byte>("LeaveCredits")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeAccountInfo.AccountInfoModel", b =>
                {
                    b.Property<Guid>("EmployeeAccountInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("DateHired")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<byte>("EmploymentType")
                        .HasColumnType("tinyint");

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailingAddress")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("MiddleInitial")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<byte>("Nationality")
                        .HasColumnType("tinyint");

                    b.Property<string>("PagIbigIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhilHealthIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SSSIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("TaxIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeAccountInfoId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AccountInfoModel");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeAttendanceLog.EmployeeAttendanceLogModel", b =>
                {
                    b.Property<Guid>("EmployeeAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("EventType")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("TimeStamp")
                        .HasColumnType("time");

                    b.HasKey("EmployeeAttendanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeAttendanceLogModel");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeAttendanceRequest.EmployeeAttendanceRequestModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("BreakEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("BreakStart")
                        .HasColumnType("time");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RequestDate")
                        .HasColumnType("date");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("TimeIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeOut")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeAttendanceRequestModel");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeEvaluatedAttendance.EmployeeEvaluatedAttendanceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActualWorkHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BreakTimeInReference")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BreakTimeOutReference")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<byte>("DayStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EvaluationTimeStamp")
                        .HasColumnType("datetime");

                    b.Property<decimal>("ExpectedWorkHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NightDifferentialHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("OvertimeVerificationStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("TimeInReference")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TimeOutReference")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeEvaluatedAttendanceModel");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeLeave.EmployeeLeaveModel", b =>
                {
                    b.Property<Guid>("EmployeeLeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfAbsenceStart")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfFiling")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfReturn")
                        .HasColumnType("date");

                    b.Property<short>("Duration")
                        .HasColumnType("smallint");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("EmployeeLeaveId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeLeaveModel");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeePayslip.EmployeePayslipModel", b =>
                {
                    b.Property<Guid>("EmployeePayslipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AppliedHourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AppliedLegalHolidayRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AppliedNDRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AppliedOvertimeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CompanyLoans")
                        .HasColumnType("money");

                    b.Property<decimal>("DecemberHDMF")
                        .HasColumnType("money");

                    b.Property<decimal>("DecemberSSS")
                        .HasColumnType("money");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GovernmentLoans")
                        .HasColumnType("money");

                    b.Property<decimal>("GrossPay")
                        .HasColumnType("money");

                    b.Property<decimal>("HDMF")
                        .HasColumnType("money");

                    b.Property<decimal>("HolidayHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoursWorkedRegular")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Legal13thMonthPay")
                        .HasColumnType("money");

                    b.Property<decimal>("LoadAllowance")
                        .HasColumnType("money");

                    b.Property<decimal>("MealAllowance")
                        .HasColumnType("money");

                    b.Property<decimal>("NDOnWorkingDayHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("money");

                    b.Property<decimal>("OTHoursWorkedRegular")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PHIC")
                        .HasColumnType("money");

                    b.Property<decimal>("PaidLeaveHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PayDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PerfectAttendanceBonus")
                        .HasColumnType("money");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("money");

                    b.Property<decimal>("UTMinutes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UtilityAllowance")
                        .HasColumnType("money");

                    b.Property<decimal>("WithholdingTax")
                        .HasColumnType("money");

                    b.HasKey("EmployeePayslipId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeePayslipModel");
                });

            modelBuilder.Entity("DomainLayer.Models.Holiday.HolidayModel", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("HolidayId");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("DomainLayer.Models.Role.RoleModel", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DomainLayer.Models.User.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DomainLayer.Models.Admin.AdminModel", b =>
                {
                    b.HasOne("DomainLayer.Models.User.UserModel", "User")
                        .WithOne("Admin")
                        .HasForeignKey("DomainLayer.Models.Admin.AdminModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.Contractor.ContractorModel", b =>
                {
                    b.HasOne("DomainLayer.Models.User.UserModel", "User")
                        .WithOne("Contractor")
                        .HasForeignKey("DomainLayer.Models.Contractor.ContractorModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.ContractorAttendanceLog.ContractorAttendanceLogModel", b =>
                {
                    b.HasOne("DomainLayer.Models.Contractor.ContractorModel", "Contractor")
                        .WithMany("ContractorAttendanceLogs")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("DomainLayer.Models.ContractorPayslip.ContractorPayslipModel", b =>
                {
                    b.HasOne("DomainLayer.Models.Contractor.ContractorModel", "Contractor")
                        .WithMany("ContractorPayslips")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("DomainLayer.Models.Employee.EmployeeModel", b =>
                {
                    b.HasOne("DomainLayer.Models.User.UserModel", "User")
                        .WithOne("Employee")
                        .HasForeignKey("DomainLayer.Models.Employee.EmployeeModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeAccountInfo.AccountInfoModel", b =>
                {
                    b.HasOne("DomainLayer.Models.User.UserModel", "User")
                        .WithOne("AccountInfo")
                        .HasForeignKey("DomainLayer.Models.EmployeeAccountInfo.AccountInfoModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeAttendanceLog.EmployeeAttendanceLogModel", b =>
                {
                    b.HasOne("DomainLayer.Models.Employee.EmployeeModel", "Employee")
                        .WithMany("EmployeeAttendanceLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeAttendanceRequest.EmployeeAttendanceRequestModel", b =>
                {
                    b.HasOne("DomainLayer.Models.Employee.EmployeeModel", "Employee")
                        .WithMany("EmployeeAttendanceRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeEvaluatedAttendance.EmployeeEvaluatedAttendanceModel", b =>
                {
                    b.HasOne("DomainLayer.Models.Employee.EmployeeModel", "Employee")
                        .WithMany("EmployeeEvaluatedAttendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeLeave.EmployeeLeaveModel", b =>
                {
                    b.HasOne("DomainLayer.Models.Employee.EmployeeModel", "Employee")
                        .WithMany("EmployeeLeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeePayslip.EmployeePayslipModel", b =>
                {
                    b.HasOne("DomainLayer.Models.Employee.EmployeeModel", "Employee")
                        .WithMany("EmployeePayslips")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DomainLayer.Models.User.UserModel", b =>
                {
                    b.HasOne("DomainLayer.Models.Department.DepartmentModel", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.Role.RoleModel", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DomainLayer.Models.Contractor.ContractorModel", b =>
                {
                    b.Navigation("ContractorAttendanceLogs");

                    b.Navigation("ContractorPayslips");
                });

            modelBuilder.Entity("DomainLayer.Models.Department.DepartmentModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DomainLayer.Models.Employee.EmployeeModel", b =>
                {
                    b.Navigation("EmployeeAttendanceLogs");

                    b.Navigation("EmployeeAttendanceRequests");

                    b.Navigation("EmployeeEvaluatedAttendances");

                    b.Navigation("EmployeeLeaveRequests");

                    b.Navigation("EmployeePayslips");
                });

            modelBuilder.Entity("DomainLayer.Models.Role.RoleModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DomainLayer.Models.User.UserModel", b =>
                {
                    b.Navigation("AccountInfo");

                    b.Navigation("Admin");

                    b.Navigation("Contractor");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
